#!/bin/sh
set -eu

LLPS_CR="$(printf '\r')"
LLPS_NEWLINE='
'

llps_reject_multiline_value() {
    case "$2" in
        *"$LLPS_CR"*|*"$LLPS_NEWLINE"*)
            printf '%s\n' "llps-docker-entrypoint: $1 must be a single-line value" >&2
            exit 64
            ;;
    esac
}

llps_reject_multiline_env() {
    eval "LLPS_ENV_VALUE=\${$1-}"
    llps_reject_multiline_value "$1" "$LLPS_ENV_VALUE"
}

for LLPS_ENV_NAME in \
    LLPS_CONFIG \
    LLPS_LISTEN_HOST \
    LLPS_LISTEN_PORT \
    LLPS_TARGET_HOST \
    LLPS_TARGET_IP \
    LLPS_TARGET_PORT \
    LLPS_MAX_CLIENTS \
    LLPS_BUFFER_SIZE \
    LLPS_LISTEN_BACKLOG \
    LLPS_ACCEPT_BATCH_MAX \
    LLPS_SESSION_IDLE_TIMEOUT_MS \
    LLPS_MAX_SESSIONS_PER_CLIENT_IP \
    LLPS_MAX_NEW_SESSIONS_PER_CLIENT_IP_PER_WINDOW \
    LLPS_CLIENT_IP_RATE_WINDOW_MS \
    LLPS_CLIENT_PREFACE_TIMEOUT_MS \
    LLPS_PROTOCOL_HANDSHAKE_GATE_ENABLED \
    LLPS_PAYLOAD_ECC_ENABLED \
    LLPS_IP_AUDIT_ENABLED \
    LLPS_IP_AUDIT_PATH \
    LLPS_AUDIT_MAC_ENABLED \
    LLPS_AUDIT_MAC_KEY_PATH \
    LLPS_REQUIRE_READINESS \
    LLPS_PLATFORM_SAFETY_FLAGS \
    LLPS_PLATFORM_SAFETY_EVIDENCE_ID \
    LLPS_PLATFORM_ATTESTATION_FINGERPRINT \
    LLPS_PLATFORM_OBSERVATION_DIGEST \
    LLPS_PLATFORM_EVIDENCE_MODE \
    LLPS_PHYS_MEM_DOMAIN0 \
    LLPS_PHYS_MEM_DOMAIN1 \
    LLPS_PHYS_MEM_DOMAIN2 \
    LLPS_HW_TMR_DOMAIN0 \
    LLPS_HW_TMR_DOMAIN1 \
    LLPS_HW_TMR_DOMAIN2 \
    LLPS_HW_TMR_VOTER_DOMAIN \
    LLPS_SOFTWARE_ECC_ENABLED \
    LLPS_SOFTWARE_ECC_CONTROLLER_COUNT \
    LLPS_SOFTWARE_ECC_DIMM_COUNT \
    LLPS_SOFTWARE_ECC_SCRUB_RATE \
    LLPS_SOFTWARE_ECC_CONTROLLER_CORRECTED_ERROR_COUNT \
    LLPS_SOFTWARE_ECC_CONTROLLER_UNCORRECTED_ERROR_COUNT \
    LLPS_SOFTWARE_ECC_DIMM_CORRECTED_ERROR_COUNT \
    LLPS_SOFTWARE_ECC_DIMM_UNCORRECTED_ERROR_COUNT \
    LLPS_SOFTWARE_NUMA_ENABLED \
    LLPS_SOFTWARE_NUMA_MEMTOTAL_KIB \
    LLPS_SOFTWARE_NUMA_LOCAL_DISTANCE \
    LLPS_SOFTWARE_NUMA_REMOTE_DISTANCE \
    LLPS_SOFTWARE_FAULT_INJECTION_MODE \
    LLPS_EVIDENCE_MAC_ENABLED \
    LLPS_EVIDENCE_MAC_KEY_PATH
do
    llps_reject_multiline_env "$LLPS_ENV_NAME"
done

CONFIG_PATH="${LLPS_CONFIG:-/tmp/llps.yml}"

if [ -z "${LLPS_CONFIG:-}" ]; then
    LISTEN_HOST="${LLPS_LISTEN_HOST:-0.0.0.0}"
    LISTEN_PORT="${LLPS_LISTEN_PORT:-25565}"
    TARGET_HOST="${LLPS_TARGET_HOST:-${LLPS_TARGET_IP:-127.0.0.1}}"
    TARGET_PORT="${LLPS_TARGET_PORT:-25566}"
    MAX_CLIENTS="${LLPS_MAX_CLIENTS:-256}"
    BUFFER_SIZE="${LLPS_BUFFER_SIZE:-4096}"
    LISTEN_BACKLOG="${LLPS_LISTEN_BACKLOG:-256}"
    ACCEPT_BATCH_MAX="${LLPS_ACCEPT_BATCH_MAX:-32}"
    SESSION_IDLE_TIMEOUT_MS="${LLPS_SESSION_IDLE_TIMEOUT_MS:-30000}"
    MAX_SESSIONS_PER_CLIENT_IP="${LLPS_MAX_SESSIONS_PER_CLIENT_IP:-0}"
    MAX_NEW_SESSIONS_PER_CLIENT_IP_PER_WINDOW="${LLPS_MAX_NEW_SESSIONS_PER_CLIENT_IP_PER_WINDOW:-0}"
    CLIENT_IP_RATE_WINDOW_MS="${LLPS_CLIENT_IP_RATE_WINDOW_MS:-1000}"
    CLIENT_PREFACE_TIMEOUT_MS="${LLPS_CLIENT_PREFACE_TIMEOUT_MS:-0}"
    PROTOCOL_HANDSHAKE_GATE_ENABLED="${LLPS_PROTOCOL_HANDSHAKE_GATE_ENABLED:-0}"
    PAYLOAD_ECC_ENABLED="${LLPS_PAYLOAD_ECC_ENABLED:-1}"
    IP_AUDIT_ENABLED="${LLPS_IP_AUDIT_ENABLED:-1}"
    IP_AUDIT_PATH="${LLPS_IP_AUDIT_PATH:-/tmp/llps-ip-audit.pxf}"
    AUDIT_MAC_ENABLED="${LLPS_AUDIT_MAC_ENABLED:-0}"
    AUDIT_MAC_KEY_PATH="${LLPS_AUDIT_MAC_KEY_PATH:-/run/llps-secrets/llps-audit.key}"
    REQUIRE_READINESS="${LLPS_REQUIRE_READINESS:-0}"
    PLATFORM_FLAGS="${LLPS_PLATFORM_SAFETY_FLAGS:-7}"
    EVIDENCE_ID="${LLPS_PLATFORM_SAFETY_EVIDENCE_ID:-42424242}"
    ATTESTATION="${LLPS_PLATFORM_ATTESTATION_FINGERPRINT:-1519046679}"
    OBSERVATION="${LLPS_PLATFORM_OBSERVATION_DIGEST:-0}"
    EVIDENCE_MODE="${LLPS_PLATFORM_EVIDENCE_MODE:-synthetic}"
    EVIDENCE_MAC_ENABLED="${LLPS_EVIDENCE_MAC_ENABLED:-0}"
    EVIDENCE_MAC_KEY_PATH="${LLPS_EVIDENCE_MAC_KEY_PATH:-/run/llps-secrets/llps-evidence.key}"

    cat > "$CONFIG_PATH" <<EOF_CONFIG
max_clients: $MAX_CLIENTS
buffer_size: $BUFFER_SIZE
listen_host: $LISTEN_HOST
listen_port: $LISTEN_PORT
target_host: $TARGET_HOST
target_port: $TARGET_PORT
listen_backlog: $LISTEN_BACKLOG
accept_batch_max: $ACCEPT_BATCH_MAX
session_idle_timeout_ms: $SESSION_IDLE_TIMEOUT_MS
max_sessions_per_client_ip: $MAX_SESSIONS_PER_CLIENT_IP
max_new_sessions_per_client_ip_per_window: $MAX_NEW_SESSIONS_PER_CLIENT_IP_PER_WINDOW
client_ip_rate_window_ms: $CLIENT_IP_RATE_WINDOW_MS
client_preface_timeout_ms: $CLIENT_PREFACE_TIMEOUT_MS
protocol_handshake_gate_enabled: $PROTOCOL_HANDSHAKE_GATE_ENABLED
payload_ecc_enabled: $PAYLOAD_ECC_ENABLED
ip_audit_enabled: $IP_AUDIT_ENABLED
ip_audit_path: $IP_AUDIT_PATH
audit_mac_enabled: $AUDIT_MAC_ENABLED
audit_mac_key_path: $AUDIT_MAC_KEY_PATH
require_readiness: $REQUIRE_READINESS
platform_safety_flags: $PLATFORM_FLAGS
platform_safety_evidence_id: $EVIDENCE_ID
platform_attestation_fingerprint: $ATTESTATION
platform_observation_digest: $OBSERVATION
platform_evidence_mode: $EVIDENCE_MODE
phys_mem_domain0: ${LLPS_PHYS_MEM_DOMAIN0:-11}
phys_mem_domain1: ${LLPS_PHYS_MEM_DOMAIN1:-22}
phys_mem_domain2: ${LLPS_PHYS_MEM_DOMAIN2:-33}
hw_tmr_domain0: ${LLPS_HW_TMR_DOMAIN0:-0}
hw_tmr_domain1: ${LLPS_HW_TMR_DOMAIN1:-0}
hw_tmr_domain2: ${LLPS_HW_TMR_DOMAIN2:-0}
hw_tmr_voter_domain: ${LLPS_HW_TMR_VOTER_DOMAIN:-0}
software_ecc_enabled: ${LLPS_SOFTWARE_ECC_ENABLED:-1}
software_ecc_controller_count: ${LLPS_SOFTWARE_ECC_CONTROLLER_COUNT:-1}
software_ecc_dimm_count: ${LLPS_SOFTWARE_ECC_DIMM_COUNT:-8}
software_ecc_scrub_rate: ${LLPS_SOFTWARE_ECC_SCRUB_RATE:-4096}
software_ecc_controller_corrected_error_count: ${LLPS_SOFTWARE_ECC_CONTROLLER_CORRECTED_ERROR_COUNT:-0}
software_ecc_controller_uncorrected_error_count: ${LLPS_SOFTWARE_ECC_CONTROLLER_UNCORRECTED_ERROR_COUNT:-0}
software_ecc_dimm_corrected_error_count: ${LLPS_SOFTWARE_ECC_DIMM_CORRECTED_ERROR_COUNT:-0}
software_ecc_dimm_uncorrected_error_count: ${LLPS_SOFTWARE_ECC_DIMM_UNCORRECTED_ERROR_COUNT:-0}
software_numa_enabled: ${LLPS_SOFTWARE_NUMA_ENABLED:-1}
software_numa_memtotal_kib: ${LLPS_SOFTWARE_NUMA_MEMTOTAL_KIB:-1048576}
software_numa_local_distance: ${LLPS_SOFTWARE_NUMA_LOCAL_DISTANCE:-10}
software_numa_remote_distance: ${LLPS_SOFTWARE_NUMA_REMOTE_DISTANCE:-20}
software_fault_injection_mode: ${LLPS_SOFTWARE_FAULT_INJECTION_MODE:-full}
evidence_mac_enabled: $EVIDENCE_MAC_ENABLED
evidence_mac_key_path: $EVIDENCE_MAC_KEY_PATH
EOF_CONFIG
fi

exec /opt/llps/llps -c "$CONFIG_PATH" "$@"
